export const TYPE = {
    GET_CURRENTLY_PLAY_TRACK: 'GET_CURRENTLY_PLAY_TRACK',
    SET_CURRENT_TRACK: 'SET_CURRENT_TRACK',
    SKIP_TO_NEXT: 'SKIP_TO_NEXT',
    SKIP_TO_PREVIOUS: 'SKIP_TO_PREVIOUS',
    PLAY_TRACK: 'PLAY_TRACK',
    UPDATE_PLAYER_TRACK_STATE: 'UPDATE_PLAYER_TRACK_STATE',
    SET_VOLUME: 'SET_VOLUME'
}